[keybinds]

# Noctalia Specific Binds
"Mod" = "spawn:noctalia msg panel-toggle control-center"
"Mod+Space" = "spawn:noctalia msg panel-toggle launcher"
"Mod+V" = "spawn:noctalia msg panel-toggle clipboard"
"Mod+Y" = "spawn:noctalia msg panel-toggle wallpaper"
"Mod+N" = "spawn:noctalia msg panel-toggle control-center notifications"
"Mod+Shift+N" = "spawn:noctalia msg panel-toggle noctalia/notes:panel"
"Mod+R" = "spawn:noctalia msg screenshot-region"
"Mod+Shift+R" = "spawn:noctalia msg screenshot-fullscreen"
"Mod+X" = "spawn:noctalia msg panel-toggle session"
"Mod+Comma" = "spawn:noctalia msg settings-toggle"
"Alt+Tab" = "spawn:noctalia msg window-switcher"

# Binds intended to work while locked use the table form.
"XF86MonBrightnessDown" = { action = "spawn:noctalia msg brightness-down 10", allow_when_locked = true }
"XF86MonBrightnessUp" = { action = "spawn:noctalia msg brightness-up 10", allow_when_locked = true }
