-- Generated by hyprconf2lua v1.3.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Auto-generated by DMS - do not edit manually

hl.env("HYPRCURSOR_THEME", "capitaine-cursors")

hl.env("XCURSOR_THEME", "capitaine-cursors")

hl.env("HYPRCURSOR_SIZE", 32)

hl.env("XCURSOR_SIZE", 32)
