-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "DP-1", mode = "2560x1440@165.080", position = "0x0", scale = 1, vrr = 1, bitdepth = 10, sdrbrightness = 1.5, sdrsaturation = 1.1 })
