--target-colorspace-hint-mode=source
osc=no
tone-mapping=st2094-40
hdr-compute-peak=yes

profile=gpu-hq
vo=gpu-next

dscale=mitchell
linear-downscaling=yes

save-position-on-quit=yes
watch-later-options=start
