[colors]
background = "#1e1f27FF"
text_primary = "#e2e1ecFF"
text_muted = "#c4c5d6FF"
accent_primary = "#b8c3ffFF"
accent_secondary = "#b9c4fcFF"
warning = "#f4aeffFF"
error = "#ffb4abFF"
insert_hint = "#f4aeff80"
backdrop = "#444654FF"

[colors.border]
focused = "#b8c3ffFF"
unfocused = "#444654FF"
outer = "#12131aFF"

[colors.overview]
background_tint = "#12131a88"
badge = "#b8c3ffFF"
workspace_background = "#12131aFF"

[[window_rule]]
match.is_scratchpad = true
border_color_focused = "#f4aeffFF"
border_color_unfocused = "#8a2fa0FF"
