[config]
# ...
[theme.templates.user.obs]
input_path = '~/.config/matugen/templates/matugen.obt'
output_path = '~/.config/obs-studio/themes/matugen.obt'
# ...
[theme.templates.user.millennium]
input_path = '~/.config/matugen/templates/steammat.css'
output_path = '~/.steam/steam/steamui/skins/Material-Theme/css/main/colors/matugen.css'
# ...
[theme.templates.user.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'
# ...
[theme.templates.user.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/your-theme'
post_hook = 'pkill -USR1 cava'
# ...
[theme.templates.user.spotify]
input_path = '~/.config/matugen/templates/spicetify.ini'
output_path = '~/.config/spicetify/Themes/Sleek/color.ini'
post_hook = 'spicetify refresh'
# ...
[theme.templates.user.kvantum_kvconfig]
input_path = '~/.config/matugen/templates/kvantum-colors.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[theme.templates.user.kvantum_svg]
input_path = '~/.config/matugen/templates/kvantum-colors.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'
# ...
[theme.templates.user.iisddmtheme]
input_path = '~/.config/ii-sddm-theme/SddmColors.qml'
output_path = '~/.config/ii-sddm-theme/Colors.qml'
post_hook = 'sudo ~/.config/ii-sddm-theme/sddm-theme-apply.sh &'
# ...
[theme.templates.user.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'
# ...
[theme.templates.user.opencode]
input_path = '~/.config/matugen/templates/opencode-colors.json'
output_path = '~/.config/opencode/themes/matugen.json'
# ...
[theme.templates.user.prismlauncher]
input_path = '~/.config/matugen/templates/prismlauncher.json'
output_path = '~/.local/share/PrismLauncher/themes/Matugen/theme.json'
# ...
[theme.templates.user.heroic]
input_path = '~/.config/matugen/templates/heroic.css'
output_path = '~/.config/heroic/themes/matugen.css'
# ...
[theme.templates.user.obsidian]
input_path = '~/.config/matugen/templates/obsidian.css'
output_path = '~/Documents/obs_vault/.obsidian/snippets/matugen.css'
# ...
[theme.templates.user.vesktop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/Equicord/themes/midnight-discord.css'
# ...
[theme.templates.user.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'
