cursor #e0e3e8
cursor_text_color #c1c7ce

foreground            #e0e3e8
background            #101417
selection_foreground  #22323f
selection_background  #b8c8d9
url_color             #97ccf9

color0   #101417
color1   #ff729d
color2   #7cf98c
color3   #fff772
color4   #7cb9ec
color5   #204d73
color6   #97ccf9
color7   #eff7ff
color8   #3e4347
color9   #ff9fbc
color10  #a5ffb1
color11  #fffaa5
color12  #a9d7ff
color13  #b8deff
color14  #d1eaff
color15  #f8fcff
