color0 #fdf8fd
color1 #ba1a1a
color2 #694fa3
color3 #625b70
color4 #7e525f
color5 #d1bcff
color6 #ccc2db
color7 #1c1b1e
color8 #7a757f
color9 #ba1a1a
color10 #694fa3
color11 #625b70
color12 #7e525f
color13 #d1bcff
color14 #ccc2db
color15 #1c1b1e

cursor                #1c1b1e
cursor_text_color     #fdf8fd
background            #fdf8fd
foreground            #1c1b1e
selection_foreground  #49454e
selection_background  #e7e0eb
active_border_color   #694fa3
inactive_border_color #e7e0eb
url_color             #694fa3

active_tab_foreground   #ffffff
active_tab_background   #694fa3
inactive_tab_foreground #49454e
inactive_tab_background #e7e0eb
cursor_trail_color      #49454e
