color0 #141316
color1 #ffb4ab
color2 #d1bcff
color3 #ccc2db
color4 #f0b8c6
color5 #d1bcff
color6 #ccc2db
color7 #e6e1e6
color8 #948f99
color9 #ffb4ab
color10 #d1bcff
color11 #ccc2db
color12 #f0b8c6
color13 #d1bcff
color14 #ccc2db
color15 #e6e1e6

cursor                #e6e1e6
cursor_text_color     #141316
background            #141316
foreground            #e6e1e6
selection_foreground  #cbc4cf
selection_background  #49454e
active_border_color   #d1bcff
inactive_border_color #49454e
url_color             #d1bcff

active_tab_foreground   #3a1d71
active_tab_background   #d1bcff
inactive_tab_foreground #cbc4cf
inactive_tab_background #49454e
cursor_trail_color      #cbc4cf
