cursor #ebdfe6
cursor_text_color #d1c3cb

foreground            #ebdfe6
background            #171216
selection_foreground  #3d2b3a
selection_background  #dabfd3
url_color             #f0b3e8

color0   #171216
color1   #ff7281
color2   #9cf078
color3   #ffde72
color4   #e39eda
color5   #6f3b68
color6   #f0b3e8
color7   #fcecf9
color8   #484047
color9   #ff9fa9
color10  #c0ffa5
color11  #ffeaa5
color12  #ffc7f7
color13  #ffd1f9
color14  #ffe1fb
color15  #fff8fe
